---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/quotes
  label: Quotes
  create: all
  match: "**/*"
  templates:
  - quote
- type: directory
  path: content/principes
  label: Principes
  create: documents
  match: "**/*"
  templates:
  - principe
- type: heading
  label: Config
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".nuxt"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn build
